title: Try my MomMom's Cookies
description: > # this means to ignore newlines until "baseurl:"
  The best cookies you can ever have
permalink: ':title/'
baseurl: "/mmc" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cyndi MacLeon # add your name
author-img: profileCentered.png # add your photo
about-author: Now taking orders... # add description
social-twitter: # add your Twitter handle
social-facebook: cyndi.burgymacleon # cmacleon # add your Facebook handle
#social-github: false # add your Github handle
#social-linkedin: false # add your Linkedin handle
social-email: cyndimacleon@gmail.com # add your Email address

# Disqus
#discus-identifier: CyndiMacLeon # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
